version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/docker_2
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - celery

  celery:
    build: .
    command: celery -A docker_2.celery worker --loglevel=INFO
    volumes:
      - .:/docker_2
    depends_on:
      - redis 

  postgres:
    image: postgres
    container_name: my_postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: satish_user
      POSTGRES_PASSWORD: Test@123
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: my_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
  
  redis:
    image: redis:latest

volumes:
  postgres_data:
