version: '3'

services:
  web:
    build: .
    command: gunicorn docker_2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/docker_2
      - static_volume:/docker_2/staticfiles
      - media_volume:/docker_2/mediafiles
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    restart: always
    command: celery -A docker_2.celery worker --loglevel=INFO
    volumes:
      - .:/docker_2
    depends_on:
      - redis
      - postgres
      - web

  postgres:
    image: postgres
    container_name: my_postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: satish_user
      POSTGRES_PASSWORD: Test@123
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: my_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
  
  redis:
    image: redis:7
  
  # Nginx server
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
