# Generated by Django 4.2.9 on 2024-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
