# Generated by Django 4.2.9 on 2024-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
